[project]
name = "hsi-biopsy"
version = "0.1.0"
description = "Hyperspectral imaging (HSI) analysis of biopsy samples"
authors = [{ name  = "Tim Mach", email = "tim.mach@tum.de" },]
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "numpy",
    "pandas",
    "scipy",
    "scikit-learn",
    "scikit-image",
    "matplotlib",
    "h5py",
    "torch",
    "ipython",
    "ipywidgets",
    "tqdm",
    "loguru",
    "torchvision",
    "wandb",
    "segmentation_models_pytorch",
    "spectral",
    "torchmetrics",
    "monai"
]

[tool.setuptools.packages.find]
where = ["src"]

[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"
